import React from "react";
import Header from "components/Header";
import Footer from "components/Footer";
import List from "components/List";
import EpisodeItem from "components/EpisodeItem";

const data = [
  {
    episode_id: 1,
    title: "Pilot",
    season: "1",
    air_date: "01-20-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Krazy-8",
      "Bogdan Wolynetz",
    ],
    episode: "1",
    series: "Breaking Bad",
  },
  {
    episode_id: 2,
    title: "Cat's in the Bag...",
    season: "1",
    air_date: "01-27-2008",
    characters: ["Walter White", "Jesse Pinkman", "Skyler White", "Walter White Jr.", "Krazy-8"],
    episode: "2",
    series: "Breaking Bad",
  },
  {
    episode_id: 3,
    title: "...And the Bag's in the River",
    season: "1",
    air_date: "02-10-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Krazy-8",
      "Gretchen Schwartz",
    ],
    episode: "3",
    series: "Breaking Bad",
  },
  {
    episode_id: 4,
    title: "Cancer Man",
    season: "1",
    air_date: "02-17-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Ken Wins",
    ],
    episode: "4",
    series: "Breaking Bad",
  },
  {
    episode_id: 5,
    title: "Gray Matter",
    season: "1",
    air_date: "02-24-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Elliott Schwarts",
      "Gretchen Swartz",
      "Badger",
    ],
    episode: "5",
    series: "Breaking Bad",
  },
  {
    episode_id: 6,
    title: "Crazy Handful of Nothin",
    season: "1",
    air_date: "03-02-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Tuco Salamanca",
    ],
    episode: "6",
    series: "Breaking Bad",
  },
  {
    episode_id: 7,
    title: "A No-Rough-Stuff-Type Deal",
    season: " 1",
    air_date: "03-09-2008",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Tuco Salamanca",
    ],
    episode: "7",
    series: "Breaking Bad",
  },
  {
    episode_id: 8,
    title: "Seven-Thirty-Seven",
    season: "2",
    air_date: "03-08-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Tuco Salamanca",
    ],
    episode: "1",
    series: "Breaking Bad",
  },
  {
    episode_id: 9,
    title: "Grilled",
    season: "2",
    air_date: "03-15-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Tuco Salamanca",
      "Hector Salamanca",
    ],
    episode: "2",
    series: "Breaking Bad",
  },
  {
    episode_id: 10,
    title: "Bit by a Dead Bee",
    season: "2",
    air_date: "03-22-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Hector Salamanca",
    ],
    episode: "3",
    series: "Breaking Bad",
  },
  {
    episode_id: 11,
    title: "Down",
    season: "2",
    air_date: "03-29-2009",
    characters: ["Walter White", "Jesse Pinkman", "Skyler White", "Walter White Jr."],
    episode: "4",
    series: "Breaking Bad",
  },
  {
    episode_id: 12,
    title: "Breakage",
    season: "2",
    air_date: "04-05-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Jane Margolis",
      "Badger",
    ],
    episode: "5",
    series: "Breaking Bad",
  },
  {
    episode_id: 13,
    title: "Peekaboo",
    season: "2",
    air_date: "04-12-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Marie Schrader",
      "Walter White Jr.",
      "Gretchen Schwartz",
    ],
    episode: "6",
    series: "Breaking Bad",
  },
  {
    episode_id: 14,
    title: "Negro y Azul",
    season: "2",
    air_date: "04-19-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Tortuga",
      "Jane Margolis",
      "Ted Beneke",
    ],
    episode: "7",
    series: "Breaking Bad",
  },
  {
    episode_id: 15,
    title: "Better Call Saul",
    season: "2",
    air_date: "04-26-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Saul Goodman",
      "Jane Margolis",
      "Badger",
    ],
    episode: "8",
    series: "Breaking Bad",
  },
  {
    episode_id: 16,
    title: "4 Days Out",
    season: "2",
    air_date: "05-03-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Saul Goodman",
      "Jane Margolis",
    ],
    episode: "9",
    series: "Breaking Bad",
  },
  {
    episode_id: 17,
    title: "Over",
    season: "2",
    air_date: "05-10-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Jane Margolis",
      "Ted Beneke",
    ],
    episode: "10",
    series: "Breaking Bad",
  },
  {
    episode_id: 18,
    title: "Mandala",
    season: "2",
    air_date: "05-17-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Saul Goodman",
      "Gustavo Fring",
      "Jane Margolis",
      "Ted Beneke",
      "Donald Margolis",
      "Combo",
    ],
    episode: "11",
    series: "Breaking Bad",
  },
  {
    episode_id: 19,
    title: "Phoenix",
    season: "2",
    air_date: "05-24-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Saul Goodman",
      "Jane Margolis",
      "Ted Beneke",
      "Donald Margolis",
    ],
    episode: "12",
    series: "Breaking Bad",
  },
  {
    episode_id: 20,
    title: "ABQ",
    season: "2",
    air_date: "05-31-2009",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Mike Erhmantraut",
      "Gustavo Fring",
      "Jane Margolis",
      "Donald Margolis",
    ],
    episode: "13",
    series: "Breaking Bad",
  },
  {
    episode_id: 21,
    title: "No Más",
    season: "3",
    air_date: "03-21-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "The cousins",
    ],
    episode: "1",
    series: "Breaking Bad",
  },
  {
    episode_id: 22,
    title: "Caballo sin Nombre",
    season: "3",
    air_date: "03-28-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Mike Ehrmantraut",
      "Hector Salamanca",
    ],
    episode: "2",
    series: "Breaking Bad",
  },
  {
    episode_id: 23,
    title: "IFT",
    season: "3",
    air_date: "04-04-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Hector Salamanca",
      "Ted Beneke",
    ],
    episode: "3",
    series: "Breaking Bad",
  },
  {
    episode_id: 24,
    title: "Green Light",
    season: "3",
    air_date: "04-11-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Mike Ehrmantraut",
      "Ted Beneke",
    ],
    episode: "4",
    series: "Breaking Bad",
  },
  {
    episode_id: 25,
    title: "Más",
    season: "3",
    air_date: "04-18-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Ted Beneke",
    ],
    episode: "5",
    series: "Breaking Bad",
  },
  {
    episode_id: 26,
    title: "Sunset",
    season: "3",
    air_date: "04-25-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Gale Boetticher",
      "The cousins",
    ],
    episode: "6",
    series: "Breaking Bad",
  },
  {
    episode_id: 27,
    title: "One Minute",
    season: "3",
    air_date: "05-02-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Saul Goodman",
      "Hector Salamanca",
      "The cousins",
      "Gale Boetticher",
    ],
    episode: "7",
    series: "Breaking Bad",
  },
  {
    episode_id: 28,
    title: "I See You",
    season: "3",
    air_date: "05-09-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Mike Ehrmantraut",
    ],
    episode: "8",
    series: "Breaking Bad",
  },
  {
    episode_id: 29,
    title: "Kafkaesque",
    season: "3",
    air_date: "05-16-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Ted Beneke",
    ],
    episode: "9",
    series: "Breaking Bad",
  },
  {
    episode_id: 30,
    title: "Fly",
    season: "3",
    air_date: "05-23-2010",
    characters: ["Walter White", "Jesse Pinkman", "a fly"],
    episode: "10",
    series: "Breaking Bad",
  },
  {
    episode_id: 31,
    title: "Abiquiu",
    season: "3",
    air_date: "05-30-2010",
    characters: [
      "Walter White",
      "Jesse Pinkman",
      "Skyler White",
      "Hank Schrader",
      "Marie Schrader",
      "Walter White Jr.",
      "Gustavo Fring",
      "Saul Goodman",
      "Jane Margolis",
    ],
    episode: "11",
    series: "Breaking Bad",
  },
];

const Episodes = () => {
  const episodes = data.map((itemData) => <EpisodeItem key={itemData.episode_id} data={itemData} />);
  return (
    <section className="wrapper">
      <Header />
      <section className="content">
        <List>{episodes}</List>
      </section>
      <Footer />
    </section>
  );
};
export default Episodes;
